Repository teamforus/forus-backend, pull requests merged in 2023-11, with the labels that each got.

#1963 Add toggle fund meta information on webshop
  app/Http/Controllers/Api/Platform/Organizations/FundsController.php
  app/Http/Requests/Api/Platform/Organizations/Funds/BaseFundRequest.php
  app/Http/Resources/FundResource.php
  app/Models/Fund.php
  app/Models/FundConfig.php
  database/migrations/2023_10_09_184103_add_hide_meta_to_fund_configs.php
Labels: priority: Medium

#1997 Fix file type for fund request clarification upload
  database/migrations/2023_11_01_150341_fix_type_for_fund_request_clarification_proof_in_files.php
Labels: priority: High

#1944 rewrite external validators page to table view
  app/Http/Controllers/Api/Platform/FundsController.php
  app/Http/Controllers/Api/Platform/Organizations/FundsController.php
  app/Http/Controllers/Api/Platform/Organizations/Products/FundsController.php
  app/Http/Controllers/Api/Platform/ProductsController.php
  app/Http/Controllers/Api/Platform/ProvidersController.php
  app/Http/Controllers/Api/Platform/SearchController.php
  app/Http/Requests/Api/Platform/Funds/IndexFundsRequest.php
  app/Http/Requests/Api/Platform/Organizations/Funds/IndexFundRequest.php
  app/Http/Requests/Api/Platform/Organizations/IndexOrganizationRequest.php
  app/Http/Requests/Api/Platform/SearchProductsRequest.php
  app/Http/Requests/Api/Platform/SearchProvidersRequest.php
  app/Http/Requests/Api/Platform/SearchRequest.php
  app/Models/Implementation.php
  app/Models/Organization.php
  app/Models/Product.php
Labels: priority: Low

#1996 Fix system notification configs
  app/Http/Resources/SystemNotificationResource.php
  app/Models/SystemNotification.php
  app/Notifications/BaseNotification.php
Labels: priority: High

#1970 remove business organization type select feature
  app/Http/Controllers/Api/Platform/OrganizationsController.php
  database/migrations/2023_10_12_005957_update_business_type_id_non_nullable_from_organizations_table.php
  routes/api-platform.php
Labels: priority: Low

#2022 Update partner bsn validation
  app/Http/Requests/Api/Platform/Funds/Requests/Records/StoreFundRequestRecordRequest.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/AssignVoucherRequest.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreBatchVoucherRequest.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreVoucherRequest.php
  app/Rules/BsnRule.php
  tests/Unit/BsnRuleTest.php
Labels: priority: Low, scope: tiny

#1984 Update 2fa tests
  phpunit.xml
  tests/Feature/FundCriteriaTest.php
  tests/Feature/Identity2FATest.php
  tests/Feature/Organization2FATest.php
  tests/Traits/MakesTestFunds.php
Labels: priority: Low
