Repository teamforus/forus-backend, pull requests merged in 2023-03, with the labels that each got.

#1614 financial overview export add product vouchers data
  app/Exports/FundsExport.php
  app/Exports/Traits/FormatsExportedData.php
  app/Providers/AppServiceProvider.php
  resources/lang/nl/export.php
Labels: priority: Low

#1696 Add sorting for the fund topups
  app/Http/Controllers/Api/Platform/Organizations/Funds/FundTopUpTransactionsController.php
  app/Http/Requests/Api/Platform/Organizations/Funds/IndexFundTopUpTransactionRequest.php
  app/Searches/FundTopUpTransactionSearch.php
  app/Searches/FundTopsUpSearch.php
Labels: priority: Medium

#1664 add has products filter for fund providers
  app/Http/Requests/Api/Platform/Organizations/Provider/IndexFundProviderRequest.php
  app/Models/FundProvider.php
Labels: priority: Low

#1702 Implementation pages add default description combine settings
  app/Http/Controllers/Api/Platform/Organizations/Implementations/ImplementationPagesController.php
  app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationPages/StoreImplementationPageRequest.php
  app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationPages/UpdateImplementationPageRequest.php
  app/Http/Resources/ImplementationPageResource.php
  app/Http/Resources/Sponsor/ImplementationPageResource.php
  app/Models/ImplementationPage.php
  database/migrations/2023_02_21_220530_add_description_default_position_to_implementation_pages_table.php
Labels: priority: Medium

#1642 Make vouchers in applicable funds after prevalidation assign
  app/Http/Controllers/Api/Platform/FundsController.php
  app/Models/Implementation.php
Labels: priority: Medium

#1705 Add extra product reservation fields
  app/Exports/ProductReservationsExport.php
  app/Http/Controllers/Api/Platform/Organizations/ProductReservationsController.php
  app/Http/Controllers/Api/Platform/OrganizationsController.php
  app/Http/Controllers/Api/Platform/ProductReservationsController.php
  app/Http/Requests/Api/Platform/Organizations/BaseOrganizationRequest.php
  app/Http/Requests/Api/Platform/Organizations/Products/BaseProductRequest.php
  app/Http/Requests/Api/Platform/Organizations/Products/StoreProductRequest.php
  app/Http/Requests/Api/Platform/Organizations/Products/UpdateProductRequest.php
  app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationRequest.php
  app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationReservationSettingsRequest.php
  app/Http/Requests/Api/Platform/ProductReservations/StoreProductReservationRequest.php
  app/Http/Resources/OrganizationResource.php
  app/Http/Resources/ProductReservationResource.php
  app/Http/Resources/ProductResource.php
  app/Http/Resources/Sponsor/SponsorProviderProductResource.php
  app/Models/Organization.php
  app/Models/Product.php
  app/Models/ProductReservation.php
  app/Models/Voucher.php
  config/forus/kvk-api.php
  database/migrations/2023_02_27_200328_add_reservation_info_fields_to_organizations_table.php
  database/migrations/2023_02_27_200458_add_reservation_info_fields_to_products_table.php
  database/migrations/2023_02_28_145258_add_extra_user_details_to_product_reservations_table.php
  database/migrations/2023_03_15_124444_remove_complete_status_from_reservations_table.php
  routes/api-platform.php
Labels: priority: Medium

#1713 Fix filter transactions by date
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/ProvidersController.php
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/TransactionsController.php
  app/Models/Organization.php
  app/Statistics/Funds/FinancialStatisticQueries.php
Labels: priority: Medium

#1687 generic search add show_on_webshop flag condition
  app/Searches/WebshopGenericSearch.php
Labels: priority: Medium

#1723 fix count products available for logged out users in some cases
  app/Http/Controllers/Api/Platform/OrganizationsController.php
  app/Http/Resources/OrganizationResource.php
  app/Http/Resources/ProductResource.php
  app/Scopes/Builders/ProductQuery.php
  database/migrations/2023_03_08_202619_add_index_to_fund_provider_products_table.php
  database/seeders/LoremDbSeeder.php
Labels: priority: Medium

#1680 Add voucher transaction batch upload tests
  app/Rules/Transaction/VoucherTransactionBatchItemAmountRule.php
  app/Scopes/Builders/VoucherTransactionQuery.php
  tests/Browser/AuthenticationTest.php
  tests/Browser/EmployeeTest.php
  tests/Browser/IdentityEmailTest.php
  tests/Browser/ProductReservationTest.php
  tests/Browser/ReimbursementTest.php
  tests/Browser/Traits/HasFrontendActions.php
  tests/Browser/VoucherTransactionBatchTest.php
  tests/Feature/VoucherTransactionBatchTest.php
  tests/Traits/MakesProductReservations.php
  tests/Traits/MakesVoucherTransaction.php
Labels: priority: Low

#1708 DigiD saml implementation
  app/Http/Controllers/DigIdController.php
  app/Http/Requests/DigID/StartDigIdRequest.php
  app/Models/Implementation.php
  app/Services/DigIdService/DigIdException.php
  app/Services/DigIdService/DigIdServiceProvider.php
  app/Services/DigIdService/Models/DigIdSession.php
  app/Services/DigIdService/Objects/DigidAuthRequestData.php
  app/Services/DigIdService/Objects/DigidAuthResolveData.php
  app/Services/DigIdService/Objects/DigidData.php
  app/Services/DigIdService/Repositories/DigIdCgiRepo.php
  app/Services/DigIdService/Repositories/DigIdSamlRepo.php
  app/Services/DigIdService/Repositories/Interfaces/DigIdRepo.php
  app/Services/DigIdService/Repositories/Interfaces/IDigIdRepo.php
  app/Services/DigIdService/TmpFile.php
  app/Services/DigIdService/migrations/2019_12_03_183700_create_digid_sessions_table.php
  app/Services/DigIdService/migrations/2021_04_16_041420_add_meta_field_to_digid_sessions_table.php
  app/Services/DigIdService/migrations/2022_12_02_085334_add_provider_column_to_digid_sessions_table.php
  app/Services/DigIdService/migrations/2022_12_13_110753_increase_digid_auth_redirect_url_length_on_digid_sessions_table.php
  app/Services/SAML2Service/Exceptions/ArtifactRequestFailedException.php
  app/Services/SAML2Service/Exceptions/ArtifactResponseEmptyException.php
  app/Services/SAML2Service/Exceptions/InvalidConfigsException.php
  app/Services/SAML2Service/Exceptions/InvalidMetadataException.php
  app/Services/SAML2Service/Exceptions/Saml2Exception.php
  app/Services/SAML2Service/Lib/Artifact.php
  app/Services/SAML2Service/Lib/SOAPClient.php
  app/Services/SAML2Service/Lib/Saml2User.php
  app/Services/SAML2Service/Lib/Settings.php
  app/Services/SAML2Service/Responses/SamlArtifactResponse.php
  app/Services/SAML2Service/SamlAuth.php
  app/Services/SAML2Service/SimpleSAML/Utils/HTTP.php
  app/Services/SAML2Service/SimpleSAML/Utils/Random.php
  app/Services/SAML2Service/SimpleSAML/Utils/System.php
  app/Services/SAML2Service/SimpleSAML/Utils/XML.php
  app/Services/SAML2Service/Utils/TmpFile.php
  composer.json
  composer.lock
  config/forus/digid.php
  config/forus/seeders/productboard.php
  config/saml.php
  database/migrations/2019_11_26_144338_add_digid_fields_to_implementations_table.php
  database/migrations/2022_12_02_075208_add_digid_saml_columns_to_implementations_table.php
  database/seeders/ImplementationsTableSeeder.php
  database/seeders/LoremDbSeeder.php
  database/seeders/db/digid_saml/.gitignore
  database/seeders/db/digid_saml/digid-saml-data.example.json
Labels: priority: Medium

#1646 Sponsor customized mail to providers
  app/Http/Controllers/Api/Platform/Organizations/Funds/IdentitiesController.php
  app/Http/Requests/Api/Platform/Organizations/Funds/Identities/IndexIdentitiesRequest.php
  app/Scopes/Builders/FundProviderQuery.php
Labels: priority: Low

#1698 Add bank holidays to check working days for payments
  app/Models/BankHoliday.php
  app/Services/BNGService/Responses/Entries/Payment.php
  composer.json
  database/migrations/2023_02_23_134404_create_bank_holidays_table.php
Labels: priority: Medium

#1738 allow to disable reservations on fund level and hide empty funds from…
  app/Http/Controllers/Api/Platform/FundsController.php
  app/Http/Controllers/Api/Platform/Organizations/FundsController.php
  app/Http/Controllers/Api/Platform/Organizations/Products/FundsController.php
  app/Http/Controllers/Api/Platform/Organizations/Provider/FundProviderController.php
  app/Http/Requests/Api/Platform/Funds/IndexFundsRequest.php
  app/Http/Resources/VoucherResource.php
  app/Models/Fund.php
  app/Models/FundConfig.php
  app/Models/Voucher.php
  app/Rules/ProductReservations/ProductIdToReservationRule.php
  app/Rules/ProductReservations/ProviderProductReservationBatchItemPermissionsRule.php
  app/Rules/ProductReservations/ProviderProductReservationBatchRule.php
  app/Scopes/Builders/ProductQuery.php
  app/Searches/FundSearch.php
  app/Searches/WebshopGenericSearch.php
  database/migrations/2023_03_28_062523_add_allow_reservations_column_to_fund_configs_table.php
Labels: priority: High

#1724 add fund request assigned mail
  app/Listeners/FundRequestSubscriber.php
  app/Mail/User/FundRequestAssignedBySupervisorMail.php
  app/Models/Employee.php
  app/Notifications/Identities/Employee/IdentityAssignedToFundRequestBySupervisorNotification.php
  app/Services/Forus/Notification/Repositories/NotificationRepo.php
  app/Services/Forus/Notification/migrations/2023_03_24_072552_increase_notification_preferences_key_length.php
  database/seeders/SystemNotificationsTableSeeder.php
  database/seeders/resources/mail_templates/notification_templates.json
  database/seeders/resources/mail_templates/notifications_identities/assigned_to_fund_request_by_supervisor.md
  resources/lang/nl/mails/system_mails.php
Labels: priority: High
