Repository teamforus/forus-backend, pull requests merged in 2023-01, with the labels that each got.

#1596 Update validator fund request UI
  app/Http/Controllers/Api/Platform/Organizations/FundRequestsController.php
  app/Http/Requests/Api/Platform/Funds/Requests/IndexFundRequestsRequest.php
  app/Http/Resources/Validator/ValidatorFundRequestResource.php
  app/Models/FundRequest.php
  app/Searches/FundRequestSearch.php
  database/seeders/LoremDbSeeder.php
Labels: priority: Medium

#1626 add some product details on voucher transaction pages
  app/Exports/VoucherTransactionsSponsorExport.php
  app/Http/Resources/Sponsor/SponsorVoucherTransactionResource.php
  app/Http/Resources/Tiny/ProductTinyResource.php
  app/Models/VoucherTransaction.php
  app/Scopes/Builders/VoucherTransactionQuery.php
Labels: priority: Low

#1629 Make client uid for voucher optional for any assign type
  app/Exports/VoucherExport.php
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/VouchersController.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/ActivationCodeVoucherRequest.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreBatchVoucherRequest.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreVoucherRequest.php
  app/Http/Resources/Sponsor/SponsorVoucherResource.php
  app/Models/Data/VoucherExportData.php
  app/Models/Voucher.php
  app/Scopes/Builders/VoucherQuery.php
  database/migrations/2022_12_23_112302_change_activation_code_uid_to_client_uid_in_vouchers.php
Labels: priority: High

#1635 Add export employees with roles
  app/Exports/EmployeesExport.php
  app/Http/Controllers/Api/Platform/Organizations/EmployeesController.php
  app/Http/Requests/Api/Platform/Organizations/Employees/IndexEmployeesRequest.php
  app/Models/RecordType.php
  app/Models/Role.php
  app/Models/Traits/RecordTranslationTrait.php
  app/Models/Traits/Translations/RecordTranslationsTrait.php
  app/Models/Traits/Translations/RoleTranslationsTrait.php
  app/Searches/BaseSearch.php
  app/Searches/EmployeesSearch.php
  resources/lang/nl/export.php
  routes/api-platform.php
Labels: priority: Low

#1636 allow updating voucher limit multipliers to a fixed amount, add it to…
  app/Events/Vouchers/VoucherLimitUpdated.php
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/VouchersController.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/UpdateVoucherRequest.php
  app/Listeners/VoucherSubscriber.php
  app/Models/Voucher.php
  app/Services/EventLogService/EventLogService.php
  config/forus/event_permissions.php
  resources/lang/en/events/voucher.php
  resources/lang/nl/events/voucher.php
Labels: priority: High

#1609 dashboard add more details about voucher transactions transfer date
  app/Exports/VoucherTransactionsSponsorExport.php
  app/Http/Requests/Api/Platform/Organizations/Transactions/BaseIndexTransactionsRequest.php
  app/Http/Resources/Sponsor/SponsorVoucherTransactionResource.php
  app/Models/VoucherTransaction.php
  app/Scopes/Builders/VoucherTransactionQuery.php
Labels: priority: Low

#1647 Add source reimbursements to voucher transaction create in sponsor dashboard
  app/Http/Controllers/Api/Platform/Organizations/ReimbursementsController.php
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/TransactionsController.php
  app/Http/Requests/Api/Platform/Organizations/Reimbursements/IndexReimbursementsRequest.php
  app/Http/Requests/Api/Platform/Organizations/Sponsor/Transactions/StoreTransactionRequest.php
  app/Models/VoucherTransaction.php
  app/Searches/ReimbursementsSearch.php
  app/Services/BankService/Models/Bank.php
  database/migrations/2023_01_17_000126_add_target_reimbursement_id_to_voucher_transactions_table.php
Labels: priority: Medium

#1637 Product reservations cancel by client enhancements
  app/Events/ProductReservations/ProductReservationCanceled.php
  app/Http/Controllers/Api/Platform/Organizations/ProductReservationsController.php
  app/Http/Controllers/Api/Platform/ProductReservationsController.php
  app/Http/Requests/Api/Platform/ProductReservations/IndexProductReservationsRequest.php
  app/Http/Requests/Api/Platform/ProductReservations/UpdateProductReservationsRequest.php
  app/Http/Resources/ProductReservationResource.php
  app/Listeners/ProductReservationSubscriber.php
  app/Models/Product.php
  app/Models/ProductReservation.php
  app/Notifications/BaseNotification.php
  app/Notifications/Organizations/ProductReservations/BaseProductReservationsNotification.php
  app/Notifications/Organizations/ProductReservations/ProductReservationCanceledNotification.php
  app/Policies/ProductReservationPolicy.php
  app/Scopes/Builders/ProductReservationQuery.php
  app/Scopes/Builders/ProductSubQuery.php
  app/Searches/ProductReservationsSearch.php
  database/migrations/2023_01_12_190100_update_reservation_status_field.php
  database/seeders/SystemNotificationsTableSeeder.php
  database/seeders/resources/mail_templates/notification_templates.json
  resources/lang/nl/states/product_reservations.php
  routes/api-platform.php
  tests/Browser/ProductReservationTest.php
  tests/Feature/ProductReservationTest.php
Labels: priority: Medium

#1653 Add voucher transaction batch
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/TransactionsController.php
  app/Http/Controllers/Api/Platform/Provider/TransactionsController.php
  app/Http/Requests/Api/Platform/Organizations/Sponsor/Transactions/StoreTransactionBatchRequest.php
  app/Http/Resources/Sponsor/SponsorVoucherTransactionResource.php
  app/Models/Voucher.php
  app/Models/VoucherTransaction.php
  app/Policies/VoucherTransactionPolicy.php
  app/Rules/Transaction/VoucherTransactionBatchItemAmountRule.php
  app/Scopes/Builders/VoucherTransactionQuery.php
  app/Searches/VoucherTransactionsSearch.php
  database/migrations/2023_01_13_170705_add_uid_to_voucher_transactions.php
  resources/lang/nl/validation.php
  routes/api-platform.php
Labels: priority: High
