Repository teamforus/forus-backend, pull requests merged in 2023-08, with the labels that each got.

#1890 Add custom reservation fields
  app/Http/Controllers/Api/Platform/Organizations/OrganizationReservationFieldsController.php
  app/Http/Controllers/Api/Platform/OrganizationsController.php
  app/Http/Controllers/Api/Platform/ProductReservationsController.php
  app/Http/Requests/Api/Platform/Organizations/OrganizationReservationFields/IndexOrganizationReservationFieldsRequest.php
  app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationReservationSettingsRequest.php
  app/Http/Requests/Api/Platform/ProductReservations/StoreProductReservationRequest.php
  app/Http/Resources/OrganizationReservationFieldResource.php
  app/Http/Resources/OrganizationResource.php
  app/Http/Resources/ProductReservationFieldValueResource.php
  app/Http/Resources/ProductReservationResource.php
  app/Models/Organization.php
  app/Models/OrganizationReservationField.php
  app/Models/ProductReservation.php
  app/Models/ProductReservationFieldValue.php
  app/Models/Voucher.php
  app/Policies/OrganizationReservationFieldPolicy.php
  app/Services/Forus/TestData/TestData.php
  config/forus/test_data/configs/default/config.php
  database/migrations/2023_07_25_211454_create_organization_reservation_fields_table.php
  database/migrations/2023_07_28_180406_create_product_reservation_field_values_table.php
  resources/lang/nl/validation.php
  routes/api-platform.php
Labels: priority: High

#1866 Add global settings 2fa funds
  app/Http/Controllers/Api/Platform/OrganizationsController.php
  app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationRequest.php
  app/Http/Resources/FundResource.php
  app/Http/Resources/Identity2FAStateResource.php
  app/Http/Resources/OrganizationResource.php
  app/Models/FundConfig.php
  app/Models/Identity.php
  app/Models/Organization.php
  database/migrations/2023_07_04_153831_add_auth_2fa_fund_fields_to_organizations_table.php
  database/migrations/2023_07_04_214605_update_auth_2fa_policy_field_in_fund_configs_table.php
  tests/Feature/Identity2FATest.php
  tests/Feature/Organization2FATest.php
Labels: priority: Medium

#1878 Add organization contacts
  app/Http/Controllers/Api/Platform/OrganizationsController.php
  app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationRequest.php
  app/Http/Resources/OrganizationContactResource.php
  app/Http/Resources/OrganizationResource.php
  app/Listeners/BankConnectionSubscriber.php
  app/Listeners/FundSubscriber.php
  app/Models/Organization.php
  app/Models/OrganizationContact.php
  database/migrations/2023_07_09_095544_create_organization_contacts_table.php
  tests/Feature/OrganizationContactsTest.php
Labels: priority: Medium

#1894 rename fund global 2fa props
  app/Http/Resources/FundResource.php
Labels: priority: Medium

#1872 Provider reservations digest add information about reservation statuses
  app/Digests/ProviderReservationsDigest.php
  config/forus/mail_styles.php
  resources/lang/nl/digests/provider_reservations.php
Labels: priority: Medium

#1900 fund formula product fallback inexisting identities
  app/Models/Fund.php
  app/Models/FundFormulaProduct.php
Labels: priority: High

#1908 changed URL of IConnect sandbox
  app/Services/IConnectApiService/IConnect.php
Labels: priority: Low

#1898 update browser auto tests for product reservations
  app/Http/Controllers/Api/Platform/Organizations/OrganizationReservationFieldsController.php
  app/Http/Controllers/Api/Platform/OrganizationsController.php
  app/Http/Resources/OrganizationBasicResource.php
  app/Http/Resources/OrganizationResource.php
  app/Http/Resources/ProductResource.php
  app/Models/Product.php
  app/Policies/OrganizationReservationFieldPolicy.php
  resources/lang/nl/validation.php
  routes/api-platform.php
  tests/Browser/ProductReservationTest.php
Labels: priority: Medium

#1888 add input refocus on reservation birth date select, update validation…
  resources/lang/nl/validation.php
Labels: priority: Medium

#1907 add cms blocks per row configuration
  app/Http/Controllers/Api/Platform/Organizations/Implementations/ImplementationPagesController.php
  app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationPages/StoreImplementationPageRequest.php
  app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationPages/UpdateImplementationPageRequest.php
  app/Http/Resources/ImplementationPageResource.php
  app/Http/Resources/Sponsor/ImplementationPageResource.php
  app/Models/ImplementationPage.php
  database/migrations/2023_08_13_215407_add_blocks_per_row_field_to_implementation_pages_table.php
Labels: priority: Medium

#1914 add country prefixes for 2fa phone authentication
  app/Http/Requests/Api/Identity/Identity2FA/StoreIdentity2FARequest.php
  tests/Feature/Identity2FATest.php
Labels: priority: Medium

#1856 add option to share sponsor notes for open payments
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/TransactionsController.php
  app/Http/Requests/Api/Platform/Organizations/Sponsor/Transactions/StoreTransactionRequest.php
  app/Http/Resources/Provider/ProviderVoucherTransactionResource.php
  app/Http/Resources/Tiny/FundTinyResource.php
  app/Models/Voucher.php
  app/Models/VoucherTransaction.php
  app/Models/VoucherTransactionNote.php
  database/migrations/2023_07_03_212615_add_shared_field_to_voucher_transaction_notes_table.php
Labels: priority: Medium

#1772 Add voucher tests
  app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreVoucherRequest.php
  app/Policies/PhysicalCardPolicy.php
  tests/Feature/VoucherTest.php
  tests/TestCases/VoucherTestCases.php
  tests/Traits/VoucherTestTrait.php
Labels: priority: Medium

#1906 change products page content to table view, add sorting
  app/Http/Requests/Api/Platform/Organizations/Products/IndexProductRequest.php
  app/Models/Product.php
  app/Scopes/Builders/ProductQuery.php
Labels: priority: Medium
