Repository teamforus/forus-backend, pull requests merged in 2023-10, with the labels that each got.

#1920 identity 2FA resource small adjustments
  app/Http/Resources/Identity2FAResource.php
Labels: priority: Medium

#1939 Add fund requests for requesters on webshop
  app/Http/Controllers/Api/Platform/FundRequests/FundRequestClarificationsController.php
  app/Http/Controllers/Api/Platform/FundRequestsController.php
  app/Http/Controllers/Api/Platform/Funds/Requests/FundRequestClarificationsController.php
  app/Http/Controllers/Api/Platform/Organizations/FundRequests/FundRequestClarificationsController.php
  app/Http/Controllers/Api/Platform/Organizations/FundRequestsController.php
  app/Http/Requests/Api/Platform/FundRequests/FundRequestClarifications/UpdateFundRequestClarificationRequest.php
  app/Http/Requests/Api/Platform/FundRequests/IndexFundRequestsRequest.php
  app/Http/Resources/FundRequestClarificationResource.php
  app/Http/Resources/Requester/FundRequestResource.php
  app/Models/FundRequest.php
  app/Notifications/Identities/FundRequest/IdentityFundRequestRecordFeedbackRequestedNotification.php
  app/Policies/FundRequestClarificationPolicy.php
  app/Policies/FundRequestPolicy.php
  app/Searches/FundRequestSearch.php
  routes/api-platform.php
  tests/Browser/FundRequestTest.php
Labels: priority: High

#1938 add records to voucher creation and add records export
  app/Exports/BIExporters/BIVouchersExporter.php
  app/Exports/VoucherExport.php
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/VouchersController.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/BaseStoreVouchersRequest.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreBatchVoucherRequest.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreVoucherRequest.php
  app/Http/Resources/Arr/ExportFieldVoucherArrResource.php
  app/Http/Resources/FundResource.php
  app/Models/Data/VoucherExportData.php
  app/Models/Fund.php
  app/Models/Voucher.php
  app/Rules/VoucherRecordsRule.php
  database/migrations/2018_04_29_032220_create_record_types_table.php
Labels: priority: High

#1952 allow activate external vouchers
  app/Policies/VoucherPolicy.php
Labels: priority: High

#1949 Adjust days before transaction information for voucher transactions
  app/Http/Resources/Provider/ProviderVoucherTransactionEmployeeResource.php
  app/Models/VoucherTransaction.php
Labels: priority: High

#1956 Fix birth date in product reservation
  app/Exports/ProductReservationsExport.php
  app/Models/ProductReservation.php
Labels: priority: High

#1951 Drop Productboard API for the feedback feature and replace it with em…
  .env.example
  app/Http/Controllers/Api/Platform/FeedbackController.php
  app/Http/Controllers/Api/Platform/ProductBoardController.php
  app/Http/Controllers/ContactFormController.php
  app/Http/Requests/Api/Platform/Feedback/StoreFeedbackRequest.php
  app/Mail/FeedbackForm/FeedbackFormMail.php
  app/Models/Implementation.php
  app/Services/Forus/TestData/TestData.php
  app/Services/ProductboardApiService/Facades/ProductboardApi.php
  app/Services/ProductboardApiService/ProductboardApi.php
  app/Services/ProductboardApiService/ProductboardApiServiceProvider.php
  config/app.php
  config/forus/notification_mails.php
  config/forus/seeders/productboard.php
  config/forus/test_data/configs/default/config.php
  config/forus/throttles.php
  database/migrations/2023_10_03_230909_remove_productboard_api_key_from_implementations_table.php
  database/seeders/ImplementationsTableSeeder.php
  resources/lang/nl/mails/system_mails.php
  resources/lang/nl/throttles/feedback_form.php
  resources/mail_templates/feedback_form.md
  routes/api-platform.php
Labels: priority: Low

#1928 Product reservations split address into multiple fields
  app/Http/Controllers/Api/Platform/ProductReservationsController.php
  app/Http/Requests/Api/Platform/ProductReservations/StoreProductReservationRequest.php
  app/Http/Requests/Api/Platform/ProductReservations/ValidateProductReservationAddressRequest.php
  app/Http/Requests/Api/Platform/ProductReservations/ValidateProductReservationFieldsRequest.php
  app/Models/ProductReservation.php
  app/Models/Voucher.php
  app/Providers/AppServiceProvider.php
  database/migrations/2023_09_11_122523_add_address_fields_to_product_reservations_table.php
  database/migrations/2023_10_10_184343_add_house_addition_field_to_product_reservations_table.php
  database/migrations/2023_10_10_191235_increase_reservation_street_field_length_in_product_reservations_table.php
  resources/lang/nl/validation.php
  routes/api-platform.php
Labels: priority: High

#1933 Add features page to dashboard
  app/Http/Controllers/Api/Platform/OrganizationsController.php
  app/Http/Resources/OrganizationFeaturesResource.php
  app/Policies/OrganizationPolicy.php
  routes/api-platform.php
Labels: priority: Medium

#1979 Synchronize composer.lock with composer.json
  composer.lock
Labels: priority: Low

#1966 update viewAny method in the employee policy to check for identity ro…
  app/Policies/EmployeePolicy.php
Labels: priority: Low

#1980 add goereeoverflakkee webshop
  config/forus/test_data/configs/default/funds.php
  config/forus/test_data/configs/default/implementations.php
Labels: priority: High

#1987 Fix system notification find template error
  app/Models/SystemNotification.php
Labels: priority: High

#1985 wcag add button link label field for implementation blocks
  app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationPages/ValidateImplementationPageBlocksRequest.php
  app/Http/Resources/ImplementationBlockResource.php
  app/Models/ImplementationBlock.php
  app/Models/ImplementationPage.php
  database/migrations/2023_10_26_083533_add_button_link_label_text_field_to_implementation_blocks_table.php
  tests/Feature/ImplementationCMSTest.php
Labels: priority: High

#1958 Update share sms request phone validation
  app/Http/Requests/Api/Platform/Share/ShareSmsRequest.php
Labels: priority: High

#1969 Add notification and email for fund request feedback received
  app/Events/FundRequestClarifications/BaseFundRequestClarificationEvent.php
  app/Events/FundRequestClarifications/FundRequestClarificationReceived.php
  app/Http/Controllers/Api/Platform/FundRequests/FundRequestClarificationsController.php
  app/Listeners/FundRequestSubscriber.php
  app/Mail/Funds/FundRequestClarifications/FundRequestClarificationReceivedMail.php
  app/Models/FundRequestRecord.php
  app/Notifications/Organizations/FundRequests/FundRequestRecordFeedbackReceivedNotification.php
  database/seeders/SystemNotificationsTableSeeder.php
  database/seeders/resources/mail_templates/notification_templates.json
  database/seeders/resources/mail_templates/notifications_fund_requests/clarification_received.md
Labels: priority: High
