Repository teamforus/forus-backend, pull requests merged in 2023-06, with the labels that each got.

#1792 Financial statistics add business types filter
  app/Exports/ProviderFinancesExport.php
  app/Http/Controllers/Api/Platform/Organizations/FundsController.php
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/ProvidersController.php
  app/Http/Requests/Api/Platform/Organizations/Funds/FinanceRequest.php
  app/Http/Requests/Api/Platform/Organizations/Sponsor/Providers/IndexProvidersRequest.php
  app/Models/BusinessType.php
  app/Models/Organization.php
  app/Models/Traits/Translations/BusinessTypeTranslationTrait.php
  app/Scopes/Builders/OrganizationQuery.php
  app/Statistics/Funds/FinancialStatistic.php
  app/Statistics/Funds/FinancialStatisticQueries.php
  resources/lang/nl/export.php
Labels: priority: Medium

#1787 Add fund search by organization name
  app/Scopes/Builders/FundQuery.php
Labels: priority: Low

#1818 fix fund request decline notifications issue
  app/Events/FundRequestRecords/BaseFundRequestRecordEvent.php
  app/Listeners/FundRequestSubscriber.php
  app/Models/FundRequest.php
  app/Models/FundRequestRecord.php
Labels: priority: Medium

#1788 add the option for validators to edit fund request records
  app/Events/FundRequestRecords/FundRequestRecordUpdated.php
  app/Events/FundRequests/BaseFundRequestEvent.php
  app/Http/Controllers/Api/Platform/Organizations/FundRequests/FundRequestRecordsController.php
  app/Http/Requests/Api/Platform/Funds/Requests/Records/UpdateFundRequestRecordRequest.php
  app/Http/Resources/OrganizationResource.php
  app/Http/Resources/Validator/ValidatorFundRequestResource.php
  app/Listeners/FundRequestSubscriber.php
  app/Models/FundRequest.php
  app/Models/FundRequestRecord.php
  app/Models/Organization.php
  app/Policies/FundRequestRecordPolicy.php
  app/Services/Forus/TestData/TestData.php
  config/forus/test_data/configs/default/config.php
  database/migrations/2023_05_14_182918_add_allow_fund_request_record_edit_to_organizations_table.php
  routes/api-platform.php
Labels: priority: Low

#1813 make the product alt text configurable and add a default value
  app/Http/Requests/Api/Platform/Organizations/Products/StoreProductRequest.php
  app/Http/Requests/Api/Platform/Organizations/Products/UpdateProductRequest.php
  app/Http/Resources/ProductResource.php
  app/Http/Resources/Sponsor/SponsorProviderProductResource.php
  app/Models/Product.php
  database/migrations/2023_06_06_184659_add_alternative_text_field_to_products_table.php
Labels: priority: Medium

#1812 add reimbursements export
  app/Exports/ReimbursementsSponsorExport.php
  app/Http/Controllers/Api/Platform/Organizations/ReimbursementCategoriesController.php
  app/Http/Controllers/Api/Platform/Organizations/ReimbursementsController.php
  app/Http/Requests/Api/Platform/Organizations/Reimbursements/Categories/StoreReimbursementCategoryRequest.php
  app/Http/Requests/Api/Platform/Organizations/Reimbursements/Categories/UpdateReimbursementCategoryRequest.php
  app/Http/Requests/Api/Platform/Organizations/Reimbursements/UpdateReimbursementRequest.php
  app/Http/Resources/ReimbursementCategoryResource.php
  app/Http/Resources/ReimbursementResource.php
  app/Http/Resources/Sponsor/SponsorReimbursementResource.php
  app/Models/Organization.php
  app/Models/Reimbursement.php
  app/Models/ReimbursementCategory.php
  app/Policies/ReimbursementCategoryPolicy.php
  app/Policies/ReimbursementPolicy.php
  app/Providers/AuthServiceProvider.php
  app/Services/Forus/TestData/TestData.php
  database/migrations/2023_05_30_053718_add_provider_name_field_to_reimbursements_table.php
  database/migrations/2023_06_07_064916_create_reimbursement_categories_table.php
  database/migrations/2023_06_07_064920_add_reimbursement_category_id_column_to_reimbursements_table.php
  database/migrations/2023_06_13_124541_add_organization_id_field_to_reimbursement_categories_table.php
  routes/api-platform.php
Labels: priority: High
