Repository teamforus/forus-backend, pull requests merged in 2023-04, with the labels that each got.

#1750 add low balance email for organizations
  app/Listeners/FundSubscriber.php
  app/Models/Organization.php
  database/migrations/2023_04_01_064548_add_low_balance_email_to_organizations_table.php
Labels: priority: High

#1734 add sorting for faq items
  app/Http/Controllers/Api/Platform/Organizations/FundsController.php
  app/Http/Controllers/Api/Platform/Organizations/Implementations/ImplementationPagesController.php
  app/Models/Faq.php
  app/Models/Traits/HasFaq.php
  database/migrations/2023_03_26_224023_add_order_to_faq_table.php
Labels: priority: Medium

#1720 Add sepa export
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/TransactionBulksController.php
  app/Http/Resources/OrganizationResource.php
  app/Http/Resources/VoucherTransactionBulkResource.php
  app/Models/Organization.php
  app/Models/VoucherTransactionBulk.php
  app/Policies/VoucherTransactionBulkPolicy.php
  database/migrations/2023_03_14_184759_add_is_exported_field_to_voucher_transaction_bulks_table.php
  database/migrations/2023_04_10_134724_add_allow_manual_bulk_processing_column_to_organizations_table.php
  database/seeders/LoremDbSeeder.php
  routes/api-platform.php
Labels: priority: Low

#1712 Add notifications for bng connection about expiration
  app/Console/Commands/BankConnectionExpirationNotifyCommand.php
  app/Console/Kernel.php
  app/Events/BankConnections/BankConnectionExpiring.php
  app/Http/Controllers/Api/Platform/Organizations/AnnouncementController.php
  app/Http/Controllers/BNGController.php
  app/Http/Requests/Api/Platform/Organizations/Announcements/IndexAnnouncementRequest.php
  app/Http/Resources/AnnouncementResource.php
  app/Http/Resources/BankConnectionResource.php
  app/Listeners/BankConnectionSubscriber.php
  app/Mail/BankConnections/BankConnectionExpiringMail.php
  app/Models/Announcement.php
  app/Models/BankConnection.php
  app/Models/Implementation.php
  app/Models/Traits/HasAnnouncements.php
  app/Notifications/Organizations/BankConnections/BankConnectionExpiringNotification.php
  app/Policies/AnnouncementPolicy.php
  app/Searches/AnnouncementSearch.php
  app/Services/BNGService/BNGService.php
  app/Services/BNGService/Responses/AccessTokenResponseValue.php
  app/Services/EventLogService/EventLogService.php
  config/forus/bng.php
  database/migrations/2023_03_06_034950_rename_session_expire_at_from_bank_connections_table.php
  database/migrations/2023_03_06_102358_update_session_expire_at_for_bng_bank_connections.php
  database/migrations/2023_03_06_114444_add_announceable_morphs_to_announcements_table.php
  database/seeders/SystemNotificationsTableSeeder.php
  database/seeders/resources/mail_templates/notification_templates.json
  database/seeders/resources/mail_templates/notifications_bank_connections/expiring.md
  resources/lang/nl/notifications/notifications_bank_connections.php
  routes/api-platform.php
Labels: priority: Medium

#1762 optimize product categories endpoint used filter
  app/Scopes/Builders/ProductQuery.php
  app/Searches/ProductCategorySearch.php
  database/migrations/2023_04_18_084035_add_indexes_to_fund_provider_product_exclusions_table.php
Labels: priority: Medium

#1754 add pending provider products to sponsor digest and digests refactoring
  app/Console/Commands/Digests/SendAllDigestsCommand.php
  app/Console/Commands/Digests/SendProviderFundsDigestCommand.php
  app/Console/Commands/Digests/SendProviderProductsDigestCommand.php
  app/Console/Commands/Digests/SendProviderReservationsDigestCommand.php
  app/Console/Commands/Digests/SendRequesterDigestCommand.php
  app/Console/Commands/Digests/SendSponsorDigestCommand.php
  app/Console/Commands/Digests/SendValidatorDigestCommand.php
  app/Console/Kernel.php
  app/Digests/BaseOrganizationDigest.php
  app/Digests/ProviderFundsDigest.php
  app/Digests/ProviderProductsDigest.php
  app/Digests/ProviderReservationsDigest.php
  app/Digests/RequesterDigest.php
  app/Digests/SponsorDigest.php
  app/Digests/ValidatorDigest.php
  app/Scopes/Builders/FundProviderQuery.php
  app/Scopes/Builders/ProductQuery.php
  app/Services/EventLogService/Models/EventLog.php
  resources/lang/nl/digests/sponsor.php
Labels: priority: Low
