Repository teamforus/forus-backend, pull requests merged in 2023-05, with the labels that each got.

#1749 Social media links
  app/Http/Controllers/Api/Platform/Organizations/Implementations/ImplementationSocialMediaController.php
  app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationSocialMedia/IndexImplementationSocialMediaRequest.php
  app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationSocialMedia/StoreImplementationSocialMediaRequest.php
  app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationSocialMedia/UpdateImplementationSocialMediaRequest.php
  app/Http/Resources/ImplementationSocialMediaResource.php
  app/Models/Implementation.php
  app/Models/ImplementationSocialMedia.php
  app/Providers/RouteServiceProvider.php
  database/migrations/2023_03_31_130028_create_implementation_social_media_table.php
  routes/api-platform.php
Labels: priority: Low

#1783 fix products query filter when the product is not excluded from all f…
  app/Scopes/Builders/ProductQuery.php
  tests/Unit/ProductExclusionsTest.php
Labels: priority: High

#1779 Fix wrong permission for implementation manager cms details
  app/Http/Resources/ImplementationPrivateResource.php
Labels: priority: Medium

#1775 Increase organizations per page
  app/Http/Requests/Api/Platform/Organizations/IndexOrganizationRequest.php
  app/Http/Resources/OrganizationResource.php
  app/Models/Organization.php
Labels: priority: Medium

#1793 Separate feature and browser tests
  .github/workflows/browser_tests.yml
  .github/workflows/unit_and_feature_tests.yml
Labels: priority: Low
