Repository teamforus/forus-backend, pull requests merged in 2023-09, with the labels that each got.

#1923 separate logs and remove auth and throttle logs
  app/Exceptions/AuthorizationJsonException.php
  app/Exceptions/Handler.php
  app/Models/VoucherTransactionBulk.php
  app/Services/BNGService/Exceptions/ApiException.php
  app/Services/DigIdService/Models/DigIdSession.php
  app/Services/KvkApiService/KvkApi.php
  config/logging.php
Labels: priority: Low

#1921 Remove reservation custom fields toggle
  app/Http/Controllers/Api/Platform/OrganizationsController.php
  app/Http/Requests/Api/Platform/ProductReservations/StoreProductReservationRequest.php
  app/Http/Resources/OrganizationResource.php
  app/Http/Resources/ProductResource.php
  app/Models/Organization.php
  app/Models/Voucher.php
  config/forus/test_data/configs/default/config.php
  database/migrations/2023_08_27_104106_remove_allow_reservation_custom_fields_from_organizations.php
Labels: priority: Medium

#1924 add system configs table and firestore endpoint
  .env.example
  app/Http/Controllers/Api/Platform/FirestoreTokensController.php
  app/Http/Requests/Api/Platform/FirestoreTokens/StoreFirestoreTokenRequest.php
  app/Models/SystemConfig.php
  composer.json
  composer.lock
  config/forus/seeders/system_configs.php
  database/migrations/2023_09_04_131212_create_system_configs_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/SystemConfigTableSeeder.php
  routes/api-platform.php
  storage/firestore/.gitignore
  storage/firestore/firestore-context.example.json
Labels: priority: Low

#1929 Fix voucher transaction notes relation with shared
  app/Models/VoucherTransaction.php
Labels: priority: High

#1918 Add fund requests on webshop for requesters
  app/Http/Controllers/Api/Platform/FundRequestsController.php
  app/Http/Controllers/Api/Platform/Organizations/FundRequestsController.php
  app/Http/Requests/Api/Platform/FundRequests/IndexFundRequestsRequest.php
  app/Http/Resources/FundRequestClarificationResource.php
  app/Http/Resources/Requester/FundRequestResource.php
  app/Models/FundRequest.php
  app/Policies/FundRequestPolicy.php
  app/Searches/FundRequestSearch.php
  routes/api-platform.php
  tests/Browser/FundRequestTest.php
Labels: priority: Medium

#1934 Add external page for external fund
  app/Http/Controllers/Api/Platform/Organizations/FundsController.php
  app/Http/Requests/Api/Platform/Organizations/Funds/BaseFundRequest.php
  app/Http/Requests/Api/Platform/Organizations/Funds/StoreFundRequest.php
  app/Http/Requests/Api/Platform/Organizations/Funds/UpdateFundRequest.php
  app/Http/Resources/FundResource.php
  app/Models/Fund.php
  database/migrations/2023_09_15_121241_add_external_page_to_funds.php
  resources/lang/nl/validation.php
Labels: priority: Medium

#1937 Add missed translation for reservation validation
  resources/lang/nl/validation.php
Labels: priority: Medium
