Repository teamforus/forus-backend, pull requests merged in 2023-07, with the labels that each got.

#1848 Change funds default order
  app/Searches/FundSearch.php
Labels: priority: High

#1839 Add BI connection
  app/Exports/BIExporters/BIEmployeesExporter.php
  app/Exports/BIExporters/BIFundIdentitiesExporter.php
  app/Exports/BIExporters/BIFundProviderFinancesExporter.php
  app/Exports/BIExporters/BIFundProvidersExporter.php
  app/Exports/BIExporters/BIFundsDetailedExporter.php
  app/Exports/BIExporters/BIFundsExporter.php
  app/Exports/BIExporters/BIReimbursementsExporter.php
  app/Exports/BIExporters/BIVoucherTransactionBulksExporter.php
  app/Exports/BIExporters/BIVoucherTransactionsExporter.php
  app/Exports/BIExporters/BIVouchersExporter.php
  app/Exports/BaseFieldedExport.php
  app/Exports/EmployeesExport.php
  app/Exports/FundIdentitiesExport.php
  app/Exports/FundProvidersExport.php
  app/Exports/FundsExport.php
  app/Exports/ProviderFinancesExport.php
  app/Exports/VoucherExport.php
  app/Exports/VoucherTransactionBulksExport.php
  app/Http/Controllers/Api/BIConnectionController.php
  app/Http/Controllers/Api/Platform/OrganizationsController.php
  app/Http/Kernel.php
  app/Http/Middleware/ClientTypeMiddleware.php
  app/Http/Requests/Api/ExportBIConnectionRequest.php
  app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationBIConnectionRequest.php
  app/Http/Resources/OrganizationResource.php
  app/Models/Organization.php
  app/Models/Voucher.php
  app/Models/VoucherTransaction.php
  app/Models/VoucherTransactionBulk.php
  app/Policies/OrganizationPolicy.php
  app/Services/BIConnectionService/BIConnection.php
  app/Services/BIConnectionService/Exporters/BaseBIExporter.php
  app/Services/BIConnectionService/Responses/UnauthorizedResponse.php
  config/forus/bi_connections.php
  config/forus/test_data/configs/default/organizations.php
  database/migrations/2023_06_22_194818_add_bi_connection_columns_to_organizations_table.php
  database/seeders/PermissionsTableSeeder.php
  database/seeders/RolePermissionsTableSeeder.php
  routes/api-platform.php
  routes/api.php
  tests/Feature/BIConnectionTest.php
  tests/TestCase.php
Labels: priority: High

#1847 digid cgi add client certificate fields to the database
  app/Models/Implementation.php
  app/Services/DigIdService/Models/DigIdSession.php
  app/Services/DigIdService/Objects/ClientTls.php
  app/Services/DigIdService/Repositories/DigIdCgiRepo.php
  app/Services/DigIdService/Repositories/DigIdSamlRepo.php
  app/Services/DigIdService/Repositories/Interfaces/DigIdRepo.php
  app/Services/Forus/TestData/TestData.php
  config/forus/test_data/configs/default/config.php
  database/migrations/2023_06_27_230557_add_digid_cert_fields_to_implementations_table.php
Labels: priority: High

#1795 Added GitHub Pull-Request template
  .github/pull_request_template.md
Labels: priority: Low

#1859 transactions details small enhancements
  app/Http/Resources/Sponsor/SponsorVoucherTransactionResource.php
Labels: priority: Low

#1863 restore fund name column in the finances overview export
  app/Exports/FundsExport.php
Labels: priority: High

#1842 Add translation for throttle transaction store
  app/Traits/ThrottleWithMeta.php
  resources/lang/nl/throttles/make_transaction.php
Labels: priority: Medium

#1838 Skip bng doubled top ups by nullable amount
  app/Console/Commands/BankProcessFundTopUpsCommand.php
  app/Models/FundTopUpTransaction.php
  app/Services/BankService/Values/BankCreditorAccount.php
  app/Services/BankService/Values/BankPayment.php
  database/migrations/2023_06_22_131115_add_creditor_iban_to_fund_top_up_transactions.php
Labels: priority: Medium

#1864 Add provider unseen messages to provider products
  app/Http/Resources/Provider/ProviderProductResource.php
  app/Http/Resources/Sponsor/SponsorProviderProductResource.php
Labels: priority: High

#1870 add fund_ids filter to funds endpoint
  app/Http/Controllers/Api/Platform/FundsController.php
  app/Http/Controllers/Api/Platform/Organizations/FundsController.php
  app/Http/Controllers/Api/Platform/Organizations/Products/FundsController.php
  app/Http/Controllers/Api/Platform/Organizations/Provider/FundProviderController.php
  app/Http/Requests/Api/Platform/Funds/IndexFundsRequest.php
  app/Http/Requests/Api/Platform/Organizations/Funds/IndexFundRequest.php
  app/Searches/FundSearch.php
Labels: priority: Medium

#1865 Hide provider with products from webshop
  app/Http/Controllers/Api/Platform/Organizations/Funds/FundProviderController.php
  app/Http/Controllers/Api/Platform/Organizations/Products/FundsController.php
  app/Http/Requests/Api/Platform/Organizations/Funds/FundProviders/UpdateFundProviderRequest.php
  app/Http/Resources/FundProviderResource.php
  app/Http/Resources/ProductFundResource.php
  app/Models/FundProvider.php
  app/Scopes/Builders/FundProviderQuery.php
  app/Scopes/Builders/FundQuery.php
  app/Scopes/Builders/ProductQuery.php
  database/migrations/2023_06_29_133825_add_excluded_to_fund_providers.php
  tests/Unit/ProductExclusionsTest.php
Labels: priority: High

#1879 Fix fund export headings
  app/Exports/FundsExport.php
Labels: priority: Low

#1780 Product reservations add archiving and throttles
  app/Http/Controllers/Api/Platform/Organizations/ProductReservationsController.php
  app/Http/Controllers/Api/Platform/ProductReservationsController.php
  app/Http/Requests/Api/Platform/Organizations/ProductReservations/IndexProductReservationsRequest.php
  app/Http/Requests/Api/Platform/ProductReservations/StoreProductReservationRequest.php
  app/Http/Resources/ProductReservationResource.php
  app/Models/ProductReservation.php
  app/Policies/ProductReservationPolicy.php
  app/Rules/ProductReservations/ProductIdToReservationRule.php
  app/Searches/ProductReservationsSearch.php
  database/migrations/2023_04_28_080510_add_archived_field_to_product_reservations_table.php
  resources/lang/en/validation.php
  resources/lang/nl/validation.php
  routes/api-platform.php
  tests/Browser/ProductReservationTest.php
  tests/Feature/ProductReservationTest.php
  tests/TestCase.php
  tests/Traits/MakesProductReservations.php
Labels: priority: Medium

#1882 Send notification about new product added to all accepted funds
  app/Listeners/ProductSubscriber.php
  app/Models/BusinessType.php
  app/Models/Implementation.php
  app/Models/Organization.php
  app/Scopes/Builders/FundProviderQuery.php
Labels: priority: High

#1880 Add deactivation sms codes for 2fa if created new one
  app/Http/Requests/Api/Identity/Identity2FA/BaseIdentity2FARequest.php
  app/Models/Identity2FA.php
  app/Models/Identity2FACode.php
  database/migrations/2023_07_20_215618_add_state_to_identity_2fa_code.php
  tests/Feature/Identity2FATest.php
Labels: priority: Medium

#1789 add email to requester when product reservation is accepted
  app/Mail/ProductReservations/ProductReservationAcceptedMail.php
  app/Notifications/Identities/ProductReservation/IdentityProductReservationAcceptedNotification.php
  database/seeders/SystemNotificationsTableSeeder.php
  database/seeders/resources/mail_templates/notification_templates.json
  database/seeders/resources/mail_templates/notifications_identities/product_reservation_accepted.md
Labels: priority: Medium
