Repository teamforus/forus-backend, pull requests merged in 2024-11, with the labels that each got.

#2345 Add amount extra cash to transactions
  app/Exports/VoucherTransactionsProviderExport.php
  app/Exports/VoucherTransactionsSponsorExport.php
  app/Http/Controllers/Api/Platform/Vouchers/TransactionsController.php
  app/Http/Requests/Api/Platform/Vouchers/Transactions/StoreVoucherTransactionRequest.php
  app/Http/Resources/Provider/ProviderVoucherTransactionEmployeeResource.php
  app/Http/Resources/Provider/ProviderVoucherTransactionResource.php
  app/Http/Resources/Sponsor/SponsorVoucherTransactionResource.php
  app/Http/Resources/Sponsor/VoucherTransactionPayoutResource.php
  app/Http/Resources/VoucherTransactionResource.php
  app/Models/VoucherTransaction.php
  config/forus/transactions.php
  database/migrations/2024_10_10_084006_add_amount_extra_cash_to_voucher_transactions.php
Labels: priority: Medium

#2377 pin 8.3
  .github/workflows/psalm.yml
  .github/workflows/unit_and_feature_tests.yml
  composer.json
  composer.lock
Labels: priority: Low

#2334 add filter per year for financial overview statistics
  app/Exports/BIExporters/BIFundsDetailedExporter.php
  app/Exports/BIExporters/BIFundsExporter.php
  app/Exports/FundsExport.php
  app/Http/Controllers/Api/Platform/Organizations/FundsController.php
  app/Http/Requests/Api/Platform/Organizations/Funds/FinanceOverviewRequest.php
  app/Http/Requests/Api/Platform/Organizations/Funds/IndexFundRequest.php
  app/Http/Resources/FundResource.php
  app/Models/Fund.php
  app/Scopes/Builders/VoucherQuery.php
  app/Statistics/Funds/FinancialOverviewStatistic.php
  app/Statistics/Funds/FinancialOverviewStatisticQueries.php
  app/Statistics/Funds/FinancialStatistic.php
  app/Statistics/Funds/FinancialStatisticQueries.php
Labels: priority: Medium

#2379 implement product update digest for sponsor
  app/Console/Commands/Digests/SendSponsorProductsUpdateDigest.php
  app/Console/Kernel.php
  app/Digests/SponsorProductUpdatesDigest.php
  app/Events/Products/ProductMonitoredFieldsUpdated.php
  app/Http/Controllers/Api/Platform/Organizations/Funds/FundProviders/ProductsController.php
  app/Http/Controllers/Api/Platform/Organizations/ProductsController.php
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/ProductsController.php
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/Providers/ProductsController.php
  app/Http/Requests/Api/Platform/Organizations/Sponsor/Products/IndexProductsRequest.php
  app/Http/Resources/Sponsor/SponsorProductResource.php
  app/Http/Resources/Tiny/FundTinyResource.php
  app/Listeners/ProductSubscriber.php
  app/Mail/Digest/DigestSponsorProductUpdatesMail.php
  app/Models/Product.php
  app/Policies/ProductPolicy.php
  app/Scopes/Builders/FundProviderProductQuery.php
  app/Scopes/Builders/FundQuery.php
  app/Scopes/Builders/ProductQuery.php
  app/Searches/ProductSearch.php
  app/Services/Forus/Notification/Repositories/NotificationRepo.php
  resources/lang/nl/digests/sponsor_product_updates.php
  routes/api-platform.php
Labels: priority: High

#2378 Add sku and ean columns to product
  app/Exports/ProductReservationsExport.php
  app/Http/Requests/Api/Platform/Organizations/Products/BaseProductRequest.php
  app/Http/Requests/Api/Platform/Organizations/Products/StoreProductRequest.php
  app/Http/Requests/Api/Platform/Organizations/Products/UpdateProductRequest.php
  app/Http/Resources/Provider/ProviderProductResource.php
  app/Http/Resources/Sponsor/SponsorProductResource.php
  app/Listeners/ProductSubscriber.php
  app/Models/Product.php
  app/Rules/EanCodeRule.php
  app/Scopes/Builders/ProductQuery.php
  database/migrations/2024_10_31_183326_add_ean_and_sku_columns_to_products.php
  resources/lang/nl/validation.php
Labels: priority: High
