Repository teamforus/forus-backend, pull requests merged in 2024-01, with the labels that each got.

#2025 Feature fund pre-checks
  app/Http/Controllers/Api/Platform/Organizations/Implementations/PreCheckController.php
  app/Http/Controllers/Api/Platform/Organizations/ImplementationsController.php
  app/Http/Controllers/Api/Platform/PreCheckController.php
  app/Http/Requests/Api/Platform/Organizations/Implementations/PreChecks/SyncPreCheckRequest.php
  app/Http/Requests/Api/Platform/Organizations/Implementations/UpdatePreCheckBannerRequest.php
  app/Http/Requests/Api/Platform/PreChecks/CalculatePreCheckRequest.php
  app/Http/Resources/FundResource.php
  app/Http/Resources/ImplementationPreChecksResource.php
  app/Http/Resources/ImplementationPrivateResource.php
  app/Http/Resources/ImplementationResource.php
  app/Http/Resources/OrganizationResource.php
  app/Media/PreCheckBannerMediaConfig.php
  app/Models/Fund.php
  app/Models/Implementation.php
  app/Models/ImplementationPage.php
  app/Models/Organization.php
  app/Models/PreCheck.php
  app/Models/PreCheckRecord.php
  app/Models/RecordType.php
  app/Policies/ImplementationPolicy.php
  app/Providers/AppServiceProvider.php
  app/Scopes/Builders/VoucherQuery.php
  database/migrations/2023_11_19_154807_create_pre_checks_table.php
  database/migrations/2023_11_19_154817_create_pre_check_records_table.php
  database/migrations/2023_11_19_210003_add_pre_check_fields_to_implementations_table.php
  database/migrations/2023_11_22_090626_add_parent_id_field_to_funds_table.php
  database/migrations/2024_01_05_165601_add_allow_pre_checks_column_to_organizations_table.php
  routes/api-platform.php
Labels: priority: Medium

#2070 Add voucher transaction note test
  tests/Feature/VoucherTransactionNoteTest.php
Labels: priority: Medium

#2035 Add reservation fields enabled to product
  app/Http/Controllers/Api/Platform/ProductReservationsController.php
  app/Http/Requests/Api/Platform/Organizations/Products/BaseProductRequest.php
  app/Http/Requests/Api/Platform/ProductReservations/StoreProductReservationRequest.php
  app/Http/Resources/ProductResource.php
  app/Http/Resources/Provider/ProviderProductResource.php
  app/Models/Product.php
  database/migrations/2023_11_30_195027_add_reservation_fields_to_products.php
Labels: priority: Low

#2071 Add validation for mollie connection profile phone
  app/Http/Requests/Api/Platform/Organizations/MollieConnectionProfiles/BaseMollieConnectionProfileRequest.php
  app/Http/Requests/Api/Platform/Organizations/MollieConnections/StoreMollieConnectionRequest.php
Labels: priority: Medium

#2091 Pre-check adjustments and fixes
  app/Http/Requests/Api/Platform/Organizations/Implementations/PreChecks/SyncPreCheckRequest.php
Labels: priority: High
