Repository teamforus/forus-backend, pull requests merged in 2024-09, with the labels that each got.

#2294 Fix 50 mins running feature tests in CI
  .github/workflows/unit_and_feature_tests.yml
  docker-compose.yml
  phpunit.xml
  tests/Feature/VoucherTransactionBatchTest.php
Labels: priority: High

#2289 Feature.website pages
  app/Http/Controllers/Api/IdentityController.php
  app/Http/Controllers/ContactFormController.php
  app/Http/Requests/Api/Contact/SendContactFormRequest.php
  resources/mail_templates/contact_form.md
Labels: priority: High

#2277 Add provider products required for funds
  app/Http/Controllers/Api/Platform/Organizations/FundsController.php
  app/Http/Controllers/Api/Platform/Organizations/Provider/FundProviderController.php
  app/Http/Requests/Api/Platform/Organizations/Funds/BaseFundRequest.php
  app/Http/Resources/FundResource.php
  app/Models/Fund.php
  app/Models/FundConfig.php
  app/Scopes/Builders/FundQuery.php
  database/migrations/2024_08_10_105803_add_provider_products_required_to_fund_configs.php
  routes/api-platform.php
Labels: priority: Medium

#2307 fix deprecated string interpolation
  app/Services/Forus/Notification/Commands/NotificationsTokensImportCommand.php
Labels: priority: Low

#2299 Rename numbered test cases to words
  tests/Browser/VoucherBatchTest.php
  tests/Feature/VoucherBatchTest.php
  tests/Feature/VoucherTest.php
  tests/TestCases/VoucherBatchTestCases.php
  tests/TestCases/VoucherTestCases.php
Labels: priority: Low

#2315 Bugfix.add missing rollback field
  database/migrations/2024_08_15_033657_add_custom_amount_and_preset_fields_to_fund_configs_table.php
Labels: priority: Medium

#2321 Add record type validation for csv prevalidations data
  app/Http/Requests/Api/Platform/Prevalidations/UploadPrevalidationsRequest.php
  app/Rules/PrevalidationDataItemRule.php
  app/Rules/PrevalidationDataRule.php
Labels: priority: Medium

#2327 fix duplicate voucher expire soon notification
  app/Console/Commands/NotifyAboutVoucherExpireCommand.php
  app/Scopes/Builders/VoucherQuery.php
  resources/lang/nl/events/voucher.php
  tests/Feature/VoucherExpireSoonNotificationTest.php
Labels: priority: High
