Repository teamforus/forus-backend, pull requests merged in 2024-12, with the labels that each got.

#2365 Add control type for record types
  app/Http/Resources/FundCriterionResource.php
  app/Http/Resources/RecordTypeResource.php
  app/Models/RecordType.php
  database/migrations/2024_10_24_090712_add_control_type_to_record_types.php
Labels: priority: Medium

#2352 add fund formula products details to pre-check
  app/Http/Controllers/Api/Platform/PreCheckController.php
  app/Models/PreCheck.php
Labels: priority: Low

#2389 Add basic tests for me app endpoints
  app/Http/Controllers/Api/Identity/RecordValidationController.php
  app/Models/Identity.php
  tests/Feature/MeAppBasicRoutersTest.php
Labels: priority: Medium

#2347 add feature for excluding funds from pre-check results
  app/Http/Controllers/Api/Platform/Organizations/Implementations/PreCheckController.php
  app/Http/Controllers/Api/Platform/PreCheckController.php
  app/Http/Requests/Api/Platform/Organizations/Implementations/PreChecks/SyncPreCheckRequest.php
  app/Http/Resources/FundResource.php
  app/Http/Resources/ImplementationPreChecksResource.php
  app/Models/Fund.php
  app/Models/FundConfig.php
  app/Models/Implementation.php
  app/Models/PreCheck.php
  database/migrations/2024_10_06_224725_add_pre_check_excluded_field_to_fund_configs_table.php
  resources/views/pdf/pre_check_totals.blade.php
Labels: priority: Medium

#2420 update seeder after adding control_type column to record types
  app/Services/Forus/TestData/TestData.php
  config/forus/test_data/configs/default/record_types.php
  database/seeders/RecordTypesTableSeeder.php
Labels: priority: High

#2421 add dependabot for the backend
  .github/dependabot.yaml
Labels: priority: Low

#2399 Add max emails rule for identity
  app/Http/Requests/Api/Identity/Emails/StoreIdentityEmailRequest.php
  app/Rules/IdentityEmailMaxRule.php
  config/forus/mail.php
  resources/lang/nl/validation.php
  tests/Feature/IdentityEmailTest.php
Labels: priority: Medium

#2387 Add not found messages when model not found
  app/Exceptions/Handler.php
  resources/lang/nl/exceptions.php
Labels: priority: Medium

#2401 Update voucher has_payouts getter
  app/Http/Resources/Sponsor/SponsorVoucherResource.php
  app/Models/Voucher.php
  app/Models/VoucherTransactionBulk.php
  tests/Feature/MollieExtraPaymentsTest.php
  tests/Feature/ProductFundLimitsTest.php
  tests/Feature/ProductReservationTest.php
  tests/Feature/VoucherHasPayoutTest.php
  tests/Feature/VoucherTransactionTransferDaysTest.php
  tests/Traits/MakesTestBankConnections.php
  tests/Traits/TestsReservations.php
Labels: priority: Medium

#2430 Restore and fix financial overview year filter
  app/Console/Commands/BankProcessFundTopUpsCommand.php
  app/Exports/FundsExport.php
  app/Http/Controllers/Api/Platform/BankConnectionsController.php
  app/Http/Controllers/Api/Platform/Organizations/BankConnectionsController.php
  app/Http/Controllers/Api/Platform/Organizations/FundsController.php
  app/Http/Controllers/BNGController.php
  app/Http/Requests/Api/Platform/Organizations/Funds/IndexFundRequest.php
  app/Http/Requests/Api/Platform/Organizations/Funds/ShowFundRequest.php
  app/Http/Resources/FundResource.php
  app/Models/BankConnection.php
  app/Models/Fund.php
  app/Models/Organization.php
  app/Models/Voucher.php
  app/Models/VoucherTransaction.php
  app/Models/VoucherTransactionBulk.php
  app/Scopes/Builders/FundQuery.php
  app/Statistics/Funds/FinancialOverviewStatistic.php
  app/Statistics/Funds/FinancialOverviewStatisticQueries.php
  app/Statistics/Funds/FinancialStatisticQueries.php
  config/forus/test_data/configs/default/funds.php
  database/migrations/2024_12_11_112327_drop_balance_provider_from_funds_table.php
  tests/Feature/FundStatisticsTest.php
Labels: Urgency: High

#2403 Fix transactions filter
  app/Searches/VoucherTransactionsSearch.php
Labels: Urgency: Medium

#2385 Fix translation exception in provider digest
  app/Digests/BaseDigest.php
  app/Digests/BaseOrganizationDigest.php
  app/Digests/ProviderFundsDigest.php
  app/Digests/ProviderProductsDigest.php
  app/Digests/RequesterDigest.php
  app/Digests/SponsorDigest.php
  app/Digests/ValidatorDigest.php
Labels: Urgency: Medium

#2448 Fund request identity
  app/Http/Controllers/Api/Platform/FundRequestsController.php
  app/Http/Controllers/Api/Platform/Funds/FundRequestsController.php
  app/Http/Controllers/Api/Platform/Organizations/FundRequestsController.php
  app/Http/Controllers/Api/Platform/PayoutsController.php
  app/Http/Requests/Api/Platform/Funds/Requests/IndexFundRequestsRequest.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php
  app/Listeners/FundRequestSubscriber.php
  app/Models/Fund.php
  app/Models/FundRequest.php
  app/Models/Identity.php
  app/Models/Voucher.php
  app/Notifications/Identities/FundRequest/BaseIdentityFundRequestNotification.php
  app/Policies/FundRequestClarificationPolicy.php
  app/Policies/FundRequestPolicy.php
  app/Policies/FundRequestRecordPolicy.php
  app/Scopes/Builders/FundRequestQuery.php
  app/Searches/FundRequestSearch.php
  database/migrations/2024_12_19_073533_add_identity_id_to_fund_requests_table.php
  tests/Browser/FundRequestTest.php
Labels: Urgency: High

#2085 Fix bng transaction links
  app/Models/BankConnection.php
  app/Services/BNGService/Responses/Pagination/PaginationLinks.php
Labels: Urgency: Low
