Repository teamforus/forus-backend, pull requests merged in 2024-07, with the labels that each got.

#2241 Up php version to 8.2
  Dockerfile
  composer.json
  composer.lock
  docker/docker-compose/php/Dockerfile
Labels: priority: Medium

#2259 change psalm error level to 8 and update markdown test to use existing…
  psalm.xml
  tests/Browser/MarkdownTableCaptionAndHeadersTest.php
Labels: priority: High

#2229 Add fund formulas tests
  app/Models/Fund.php
  tests/Browser/VoucherBatchTest.php
  tests/Feature/FundCriteriaTest.php
  tests/Feature/ReimbursementTest.php
  tests/Feature/VoucherBatchTest.php
  tests/Feature/VoucherTest.php
  tests/Traits/FundFormulaProductTestTrait.php
  tests/Traits/MakesProductReservations.php
  tests/Traits/MakesTestFundProviders.php
  tests/Traits/MakesTestFunds.php
  tests/Traits/MakesTestProducts.php
  tests/Traits/VoucherTestTrait.php
Labels: priority: Medium

#2230 fund criteria steps and rules feature
  app/Http/Requests/Api/Platform/Funds/Requests/Records/UpdateFundRequestRecordRequest.php
  app/Http/Requests/Api/Platform/Funds/Requests/StoreFundRequestRequest.php
  app/Http/Requests/Api/Platform/Prevalidations/StorePrevalidationsRequest.php
  app/Http/Resources/FundCriteriaStepResource.php
  app/Http/Resources/FundCriterionResource.php
  app/Http/Resources/FundResource.php
  app/Models/Fund.php
  app/Models/FundCriteriaStep.php
  app/Models/FundCriterion.php
  app/Models/FundCriterionRule.php
  app/Models/PreCheck.php
  app/Rules/FundRequests/BaseFundRequestRule.php
  app/Rules/FundRequests/CriterionRules/BaseCriteriaRuleTypeRule.php
  app/Rules/FundRequests/CriterionRules/CriteriaRuleTypeBoolRule.php
  app/Rules/FundRequests/CriterionRules/CriteriaRuleTypeDateRule.php
  app/Rules/FundRequests/CriterionRules/CriteriaRuleTypeEmailRule.php
  app/Rules/FundRequests/CriterionRules/CriteriaRuleTypeIbanRule.php
  app/Rules/FundRequests/CriterionRules/CriteriaRuleTypeNumericRule.php
  app/Rules/FundRequests/CriterionRules/CriteriaRuleTypeSelectNumberRule.php
  app/Rules/FundRequests/CriterionRules/CriteriaRuleTypeSelectRule.php
  app/Rules/FundRequests/CriterionRules/CriteriaRuleTypeStringRule.php
  app/Rules/FundRequests/FundRequestRecords/FundRequestRecordValueRule.php
  app/Rules/FundRequests/Sponsor/FundRequestRecordValueSponsorRule.php
  app/Rules/PrevalidationDataRule.php
  app/Rules/PrevalidationItemHasRequiredKeysRule.php
  app/Rules/PrevalidationItemRule.php
  app/Services/Forus/TestData/TestData.php
  app/helpers.php
  config/forus/test_data/configs/default/organizations.php
  database/migrations/2024_05_19_105700_create_fund_criteria_steps_table.php
  database/migrations/2024_05_20_160100_add_step_fields_to_fund_criteria_table.php
  database/migrations/2024_05_26_170125_create_fund_criterion_rules_table.php
Labels: priority: Medium

#2260 Rename vouchers to tegoeden
  resources/lang/nl/events/fund.php
  resources/lang/nl/events/loggable.php
  resources/lang/nl/events/voucher.php
Labels: priority: High

#2249 Add react to auth page
  resources/views/pages/auth/deep_link.blade.php
  resources/views/pages/layout.blade.php
  resources/views/pages/notifications/subscribed.blade.php
  resources/views/pages/notifications/unsubscribed.blade.php
Labels: priority: Medium

#2267 Bugfix/add zero to reimbursement amount validation
  app/Http/Requests/Api/Platform/Reimbursements/StoreReimbursementRequest.php
Labels: priority: Low
