Repository teamforus/forus-backend, pull requests merged in 2024-03, with the labels that each got.

#2151 Exclude archived and non-active funds criteria
  app/Http/Resources/ImplementationPreChecksResource.php
Labels: priority: Medium

#2150 Fix store reimbursement note
  app/Models/Reimbursement.php
Labels: priority: Low

#2157 optimize prevalidations list loading time
  app/Models/Prevalidation.php
  database/migrations/2024_03_08_065109_add_fund_id_and_organization_id_index_to_prevalidations_table.php
Labels: priority: High

#2099 Add fund formula product multiplier test
  app/Models/Fund.php
  tests/Feature/VoucherTest.php
  tests/Traits/VoucherTestTrait.php
Labels: priority: Low

#2137 Add branch info fields for organizations
  app/Exports/EmployeesExport.php
  app/Http/Controllers/Api/Platform/OfficesController.php
  app/Http/Controllers/Api/Platform/Organizations/EmployeesController.php
  app/Http/Controllers/Api/Platform/Organizations/OfficesController.php
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/TransactionBulksController.php
  app/Http/Controllers/Api/Platform/OrganizationsController.php
  app/Http/Controllers/Api/Platform/Vouchers/TransactionsController.php
  app/Http/Requests/Api/Platform/Organizations/Employees/BaseEmployeeRequest.php
  app/Http/Requests/Api/Platform/Organizations/Employees/StoreEmployeeRequest.php
  app/Http/Requests/Api/Platform/Organizations/Employees/UpdateEmployeeRequest.php
  app/Http/Requests/Api/Platform/Organizations/Offices/BaseOfficeRequest.php
  app/Http/Requests/Api/Platform/Organizations/Offices/IndexOfficeRequest.php
  app/Http/Requests/Api/Platform/Organizations/UpdateBankStatementFieldsRequest.php
  app/Http/Resources/EmployeeResource.php
  app/Http/Resources/OfficeResource.php
  app/Http/Resources/OrganizationResource.php
  app/Http/Resources/Provider/ProviderVoucherTransactionResource.php
  app/Models/Employee.php
  app/Models/Office.php
  app/Models/Organization.php
  app/Models/ProductReservation.php
  app/Models/Reimbursement.php
  app/Models/Voucher.php
  app/Models/VoucherTransaction.php
  app/Policies/EmployeePolicy.php
  app/Policies/OfficePolicy.php
  app/Scopes/Builders/OfficeQuery.php
  app/Scopes/Builders/VoucherTransactionQuery.php
  app/Searches/OfficeSearch.php
  database/migrations/2024_02_23_093604_add_branch_fields_to_offices_table.php
  database/migrations/2024_02_26_153013_add_office_id_field_to_employees_table.php
  database/migrations/2024_03_04_223016_add_bank_statement_fields_to_organizations_table.php
  database/migrations/2024_03_11_114933_add_branch_info_fields_to_voucher_transactions_table.php
  database/migrations/2024_03_11_131922_add_bank_reservation_number_field_to_organizations_table.php
  resources/lang/nl/export.php
  routes/api-platform.php
Labels: priority: High

#2164 Small fix for payment description generation
  app/Models/VoucherTransaction.php
Labels: priority: High

#2173 composer update
  composer.lock
Labels: priority: Low

#2177 added getBulkDetailsStatus endpoint
  app/Services/BNGService/BNGService.php
  app/Services/BNGService/Responses/BulkPaymentValue.php
  app/Services/BNGService/Responses/Value.php
Labels: priority: Medium

#2178 Add children count to financial overview
  app/Http/Resources/FundResource.php
  app/Models/Fund.php
  database/seeders/RecordTypesTableSeeder.php
Labels: priority: Medium

#2066 Add bi connection security enhancements, add 2fa for bi connections
  app/Exports/BIExporters/BIEmployeesExporter.php
  app/Exports/BIExporters/BIFundIdentitiesExporter.php
  app/Exports/BIExporters/BIFundProviderFinancesExporter.php
  app/Exports/BIExporters/BIFundProvidersExporter.php
  app/Exports/BIExporters/BIFundsDetailedExporter.php
  app/Exports/BIExporters/BIFundsExporter.php
  app/Exports/BIExporters/BIReimbursementsExporter.php
  app/Exports/BIExporters/BIVoucherTransactionBulksExporter.php
  app/Exports/BIExporters/BIVoucherTransactionsExporter.php
  app/Exports/BIExporters/BIVouchersExporter.php
  app/Http/Controllers/Api/BIConnectionController.php
  app/Http/Controllers/Api/Platform/Organizations/BIConnectionController.php
  app/Http/Controllers/Api/Platform/OrganizationsController.php
  app/Http/Requests/Api/ExportBIConnectionRequest.php
  app/Http/Requests/Api/Platform/Organizations/BIConnections/AvailableTypesBIConnectionRequest.php
  app/Http/Requests/Api/Platform/Organizations/BIConnections/IndexBIConnectionRequest.php
  app/Http/Requests/Api/Platform/Organizations/BIConnections/ResetTokenBIConnectionRequest.php
  app/Http/Requests/Api/Platform/Organizations/BIConnections/StoreBIConnectionRequest.php
  app/Http/Requests/Api/Platform/Organizations/BIConnections/UpdateBIConnectionRequest.php
  app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationRequest.php
  app/Http/Resources/BIConnectionResource.php
  app/Http/Resources/FundResource.php
  app/Http/Resources/Identity2FAStateResource.php
  app/Http/Resources/OrganizationResource.php
  app/Models/Identity.php
  app/Models/Organization.php
  app/Policies/BIConnectionPolicy.php
  app/Policies/OrganizationPolicy.php
  app/Providers/AppServiceProvider.php
  app/Providers/AuthServiceProvider.php
  app/Services/BIConnectionService/BIConnection.php
  app/Services/BIConnectionService/BIConnectionService.php
  app/Services/BIConnectionService/Exporters/BaseBIExporter.php
  app/Services/BIConnectionService/Models/BIConnection.php
  app/Services/EventLogService/EventLogService.php
  database/migrations/2023_12_23_090214_create_bi_connections_table.php
  database/migrations/2023_12_27_122518_add_2fa_restrict_bi_connections_to_organizations.php
  database/migrations/2024_03_12_124034_change_bi_connection_auth_type_column_to_enabled.php
  resources/lang/nl/validation.php
  routes/api-platform.php
  tests/Feature/BIConnectionTest.php
Labels: priority: Low
