Repository teamforus/forus-backend, pull requests merged in 2024-06, with the labels that each got.

#2224 Add fund formulas tab to funds show page
  app/Http/Resources/FundFormulaResource.php
  app/Http/Resources/FundResource.php
  app/Models/FundFormula.php
Labels: priority: Medium

#2218 Add permission to only view vouchers
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/VouchersController.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php
  app/Policies/VoucherPolicy.php
  app/Policies/VoucherRecordPolicy.php
  database/seeders/PermissionsTableSeeder.php
  database/seeders/RolePermissionsTableSeeder.php
  database/seeders/RolesTableSeeder.php
Labels: priority: High

#2238 Add tests for mollie payment method
  app/Http/Controllers/Api/Platform/Organizations/MollieConnectionController.php
  app/Policies/ProductReservationPolicy.php
  app/Services/MollieService/MollieServiceTest.php
  tests/Feature/MollieExtraPaymentsTest.php
Labels: priority: Medium

#2072 Add mollie service for testing
  app/Http/Controllers/Api/Platform/Organizations/MollieConnectionController.php
  app/Http/Controllers/MollieController.php
  app/Models/ProductReservation.php
  app/Models/ReservationExtraPayment.php
  app/Policies/ProductReservationPolicy.php
  app/Services/MollieService/Commands/BaseUpdateMollieConnectionsCommand.php
  app/Services/MollieService/Interfaces/MollieServiceInterface.php
  app/Services/MollieService/Models/MollieConnection.php
  app/Services/MollieService/MollieService.php
  app/Services/MollieService/MollieServiceLogger.php
  app/Services/MollieService/MollieServiceProvider.php
  app/Services/MollieService/MollieServiceTest.php
  app/Services/MollieService/Objects/BaseObject.php
  app/Services/MollieService/Objects/Organization.php
  app/Services/MollieService/Objects/Payment.php
  app/Services/MollieService/Objects/PaymentMethod.php
  app/Services/MollieService/Objects/Profile.php
  app/Services/MollieService/Objects/Refund.php
  app/Services/MollieService/Objects/ResourceOwner.php
  config/mollie.php
  tests/Feature/MollieExtraPaymentsTest.php
Labels: priority: High

#2210 Add unit test for payment description generation
  app/Models/VoucherTransaction.php
  resources/lang/en/bunq.php
  resources/lang/nl/bunq.php
  tests/Traits/MakesTestOrganizationOffices.php
  tests/Traits/MakesVoucherTransaction.php
  tests/Unit/PaymentDescriptionTest.php
Labels: priority: Low

#2135 React.sponsor ( merge only when sponsor react frontend releasing )
  app/Http/Controllers/Api/Platform/Organizations/ImplementationsController.php
  app/Http/Controllers/Api/Platform/Organizations/Sponsor/VouchersController.php
  app/Http/Requests/Api/Platform/Organizations/Funds/IndexFundTopUpTransactionRequest.php
  app/Http/Requests/Api/Platform/Organizations/Funds/StoreFundRequest.php
  app/Http/Requests/Api/Platform/Organizations/Implementations/UpdateImplementationEmailRequest.php
  app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php
  app/Http/Resources/FundResource.php
  app/Http/Resources/ImplementationPrivateResource.php
  app/Http/Resources/OrganizationFeaturesResource.php
  app/Http/Resources/ProviderFinancialResource.php
  app/Http/Resources/RecordTypeResource.php
  app/Http/Resources/Sponsor/SponsorProviderProductResource.php
  app/Http/Resources/Sponsor/SponsorVoucherResource.php
  app/Http/Resources/VoucherResource.php
  app/Http/Resources/VoucherTransactionBulkResource.php
  app/Models/Fund.php
  app/Models/VoucherTransactionBulk.php
  app/Policies/VoucherPolicy.php
  app/Policies/VoucherRecordPolicy.php
  app/Policies/VoucherTransactionBulkPolicy.php
  app/Rules/FundCriteria/BaseFundCriteriaRule.php
  app/Searches/FundTopUpTransactionSearch.php
  app/Searches/VoucherTransactionBulksSearch.php
  app/Statistics/Funds/FinancialStatistic.php
  config/forus/features/website.php
  database/seeders/PermissionsTableSeeder.php
  database/seeders/RolePermissionsTableSeeder.php
  database/seeders/RolesTableSeeder.php
Labels: priority: Low
