Repository teamforus/forus-backend, pull requests merged in 2024-02, with the labels that each got.

#2073 Add permission to view public implementation information
  app/Http/Controllers/Api/Platform/Organizations/ImplementationsController.php
  app/Http/Resources/ImplementationResource.php
  app/Policies/ImplementationPolicy.php
  database/seeders/PermissionsTableSeeder.php
  database/seeders/RolePermissionsTableSeeder.php
Labels: priority: Medium

#1950 Dispatch voucher assigned event on product voucher creation
  app/Listeners/VoucherSubscriber.php
  app/Models/Fund.php
Labels: priority: Medium

#2100 removed implementation manager roles
  database/seeders/RolePermissionsTableSeeder.php
  database/seeders/RolesTableSeeder.php
Labels: priority: Low

#2086 Add autotest for voucher transaction check transaction_in days
  tests/Feature/VoucherTransactionNoteTest.php
  tests/Feature/VoucherTransactionTransferDaysTest.php
Labels: priority: Low

#2095 Add mail notifications for product reservation cancel or reject
  app/Listeners/ReservationExtraPaymentSubscriber.php
  app/Mail/ProductReservations/ProductReservationCanceledMail.php
  app/Mail/ProductReservations/ProductReservationRejectedMail.php
  app/Notifications/Identities/ProductReservation/IdentityProductReservationCanceledNotification.php
  app/Notifications/Identities/ProductReservation/IdentityProductReservationRejectedNotification.php
  database/seeders/SystemNotificationsTableSeeder.php
  database/seeders/resources/mail_templates/notification_templates.json
  database/seeders/resources/mail_templates/notifications_identities/product_reservation_canceled.md
  database/seeders/resources/mail_templates/notifications_identities/product_reservation_rejected.md
  database/seeders/resources/mail_templates/notifications_products/reservation_refund_reminder.md
  resources/lang/nl/mails/reservations.php
Labels: priority: Medium

#2105 Optimize notifications table
  app/Http/Controllers/Api/Platform/NotificationsController.php
  app/Http/Resources/NotificationResource.php
  app/Mail/ImplementationMail.php
  app/Models/Implementation.php
  app/Models/Notification.php
  app/Models/NotificationTemplate.php
  app/Models/SystemNotification.php
  app/Notifications/BaseNotification.php
  app/Notifications/DatabaseChannel.php
  app/Providers/AppServiceProvider.php
  database/migrations/2021_12_02_120445_migrate_old_physical_card_request_logs.php
  database/migrations/2024_01_28_141127_add_scope_to_notifications.php
  tests/TestCase.php
Labels: priority: Medium

#2130 added missing permissions to seeder
  database/seeders/RolePermissionsTableSeeder.php
Labels: priority: Low, scope: tiny

#2138 fix precheck knock when multiple funds
  app/Models/PreCheck.php
Labels: priority: High

#2141 Add a flag for toggling record types in pre-check
  app/Http/Requests/Api/Platform/Organizations/Implementations/PreChecks/SyncPreCheckRequest.php
  app/Http/Resources/ImplementationPreChecksResource.php
  app/Models/PreCheck.php
  app/Models/RecordType.php
  database/migrations/2024_02_28_191454_add_pre_check_field_to_record_types_table.php
Labels: priority: High
